config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'users#index'
  get "/users/check_email", to: 'users#check_email'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    resources :replies
    resources :likes
    resources :posts do
      resources :comments do
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts, dependent: :destroy
	has_many :comments, through: :posts
  has_many :replies
  has_and_belongs_to_many :subcategories
	attr_accessor :password_confirmation
	before_validation :cal_age
	before_save :downcase_email
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :user_name, presence: true, length: { minimum: 6 }, uniqueness: true
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
	validates :contact_number, length: { is: 10 }
	validates :password, presence: true, length: { minimum: 6 }
	validates :age, numericality: { greater_than_or_equal_to: 0, message: 'is not valid. Please enter valid date of birth' }
	validate :valid_password

	private
		def downcase_email
			self.email = email.downcase
		end

		def valid_password
			errors.add(:base, "Password do not match") if password != password_confirmation
		end

		def cal_age
			if date_of_birth
  				self.age = ((Time.zone.now - date_of_birth.to_time) / 1.year.seconds).floor
  			else
  				errors.add(:base, "Please enter date of birth")
  			end
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_details, except: [:check_email]
  def check_email
    @user = User.find_by_email(params[:user][:email])
    respond_to do |format|
      format.json {
        render json: !@user
      }
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new 
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private 
    def user_params
      params.require(:user).permit(:user_name, :email, :date_of_birth, :contact_number, :address,
        :password, :password_confirmation, subcategory_ids: [])
    end

    def require_details
      @categories = Category.all;
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation" style="color:red">
            <h2>
                <%= pluralize(@user.errors.count, "error") %>!
            </h2>
            <div class="container">
                <ul class="list-group">
                    <% @user.errors.full_messages.each do |msg| %>
                        <li class="list-group-item"><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    <% end %>

    <div class="form-group">
        <p>
            <%= f.label :user_name %><br>
            <%= f.text_field :user_name, class: 'form-control', placeholder: 'Enter username' %>
        </p>
    </div>

    <div class="form-group">
        <p>   
            <%= f.label :email %><br>
            <%= f.email_field :email, class: 'form-control', placeholder: 'Enter email' %>
        </p>
    </div>

    <div class="form-group">
        <p>
            <%= f.label :date_of_birth %><br>
            <%= f.date_field :date_of_birth, class: 'form-control', placeholder: 'Enter date of birth' %>
        </p>
    </div>  

    <div class="form-group">
        <p>
            <%= f.label :contact_number %><br>
            <%= f.telephone_field :contact_number, class: 'form-control', placeholder: 'Enter contact number' %>
        </p>
    </div>

    <div class="form-group">
        <p>
            <%= f.label :address %><br>
            <%= f.text_area :address, class: 'form-control', placeholder: 'Enter address' %>
        </p>
    </div>

    <div class="form-group">
        <p>
            <%= f.label :password %><br>
            <%= f.password_field :password, class: 'form-control', placeholder: 'Enter new password' %>
        </p>
    </div>

    <div class="form-group">
        <p>
            <%= f.label :password_confirmation %><br>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm password' %>
        </p>
    </div>

    <div class="form-group">
        <%= select_tag(:category_id, options_from_collection_for_select(@categories, 'id', 'title'), {class: "btn mdown", include_blank: "Select Category"})%>
        <% @categories.each do |category| %>
            <div class="hide all_categories" data-category-id="<%= category.id %>">
                <% category.subcategories.each do |subcategory| %>
                    <p>
                        <%= check_box_tag "user[subcategory_ids][]", subcategory.id, false, class: 'checkbox_acc' %>
                        <%= label_tag(subcategory.id, subcategory.name) %>
                    </p>
                <% end %>
            </div>
        <% end %>
    </div>

    <p id="demo"></p>

    <div class="form-group">
        <%= f.submit 'Submit', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h2>Edit user details</h2>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="panel-group" id="accordion" style="margin-top:5px">
    <% @users.each do |user| %>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    User : <%= user.user_name %>
                    <a class="btn btn-info pull-right" data-parent="#accordion" data-toggle="collapse" href="#collapse-user-<%= user.id %>"> Posts</a>
                </h4>
            </div>
            <div id="collapse-user-<%= user.id %>" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul class="list-group">
                        <% if user.posts.any? %>
                            <div class="panel-group" id="accordion1">
                                <% user.posts.each do |post| %>
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <li class="list-group-item">
                                                    Post --> <%= post.message %>
                                                    <% if logged_in? && @current_user != user %>
                                                        <% if find_like(post.id, @current_user.id) != 0 %>
                                                            <%= link_to "Unlike", 'javascript:void(0)', id: "post_#{post.id}_likes_likebtn", class: "btn btn-default like-right-position like-btn", data: { user_id: @current_user.id, likeable_id: post.id, likeable_type: 'Post', like_id: find_like(post.id, @current_user.id) } %>
                                                        <% else %>
                                                            <%= link_to "Like", 'javascript:void(0)', id: "post_#{post.id}_likes_likebtn", class: "btn btn-default like-right-position like-btn", data: { user_id: @current_user.id, likeable_id: post.id, likeable_type: 'Post', like_id: '0' } %>
                                                        <% end %>
                                                    <% end %>
                                                    <span id="post_<%= post.id %>_likes" class="like-right-position" ><%= pluralize(post.likes.size, "like") %></span>
                                                </li>
                                                <a class="btn btn-info pull-right" data-parent="#accordion1" data-toggle="collapse" href="#collapse-post-<%= post.id %>"> Comments</a>
                                            </h4>
                                        </div>
                                        <div id="collapse-post-<%= post.id %>" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <ul class="list-group">
                                                    <% if post.comments.any? %>
                                                        <% post.comments.each do |comment| %>
                                                            <h5><li class="list-group-item"><%= comment.text %>
                                                                    <% if logged_in? && @current_user != user %>
                                                                        <% if find_comment(comment.id, @current_user.id) != 0 %>
                                                                            <%= link_to "Unlike", 'javascript:void(0)', id: "comment_#{comment.id}_likes_likebtn", class: "btn btn-default like-right-position comment-like-btn", data: { user_id: @current_user.id, likeable_id: comment.id, likeable_type: 'Comment', like_id: find_comment(comment.id, @current_user.id)} %>
                                                                        <% else %>
                                                                            <%= link_to "Like", 'javascript:void(0)', id: "comment_#{comment.id}_likes_likebtn", class: "btn btn-default like-right-position comment-like-btn", data: { user_id: @current_user.id, likeable_id: comment.id, likeable_type: 'Comment', like_id: '0' } %>
                                                                        <% end %>
                                                                    <% end %>
                                                                    <span id="comment_<%= comment.id %>_likes" class="like-right-position" ><%= pluralize(comment.likes.size, "like") %></span>
                                                                </li>
                                                            </h5>
                                                        <% end %>
                                                    <% else %>
                                                        <h5><li class="list-group-item">No Comments</li></h5>
                                                    <% end %>             
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                <% end %>
                            </div>
                        <% else %>
                            <h5><li class="list-group-item"><%= user.user_name %> do not have any post!</li></h5>
                        <% end %>             
                    </ul>
                </div>
            </div>
        </div>
    <% end %>
</div>


<% if false %>
<div>
    <% @users.each do |user| %>
        <h4>
            <strong>
                User Name : <%= user.user_name %>
            </strong>
        </h4>
        <% user.posts.each do |post| %>
            <div class="post_side">
                <h4>Post --> <%= post.message %></h4>
                    <% if logged_in? && @current_user != user %>
                        <%= render 'replies/form', locals: { replyable_id: post.id, replyable_type: 'Post' } %>
                    <% end %>
            </div>
            <% if post.comments.any? %>
                <h4 class="padding_2">Comments</h4>
                <div class="comment_side">
                    <% post.comments.each do |comment| %>
                        <h4 class="padding_3"><%= comment.text %></h4>
                            <% if logged_in? && @current_user != user %>
                                <%= render 'replies/form', locals: { replyable_id: comment.id, replyable_type: 'Comment' } %>
                            <% end %>
                    <% end %>
                </div>
            <% end %>
        <% end %>
    <% end %>
</div>
<% end %>

app/views/users/new.html.erb
<% if logged_in? %>
	<strong>You are already logged in :- </strong>
	<%= link_to 'Your Profile', user_path(@current_user) %>
<% else %>
    <h1>Enter user details</h1>
    <%= render 'form' %>
<% end %>

app/views/users/show.html.erb
<h2>Your Details
    <%= link_to(raw('<span class="glyphicon glyphicon-list"></span> All Posts'), user_posts_path(@user), class: "btn btn-info pull-right") %>     
    <%= link_to(raw('<span class="glyphicon glyphicon-plus"></span> Add Posts'), new_user_post_path(@user), class: "btn btn-info pull-right") %>
</h2>
<table class="table">
    <tr>	
        <td>Name</td>
        <td><%= @user.user_name %></td>
    </tr>
    <tr>	
        <td>Email</td>
        <td><%= @user.email %></td>
    </tr>
    <tr>	
        <td>Date Of Birth</td>
        <td><%= @user.date_of_birth %></td>
    </tr>
    <tr>	
        <td>Age</td>
        <td><%= @user.age %></td>
    </tr>
    <tr>
        <td>Contact Number</td>
        <td><%= @user.contact_number %></td>
    </tr>
    <tr>
        <td>Address</td>
        <td><%= @user.address %></td>
    </tr>
</table>
<p align="center">
    <%= link_to(raw('<span class="glyphicon glyphicon-edit"></span> Edit User'), edit_user_path, class: "btn btn-primary") %>
</p>