config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'users#index'
  get "/users/check_email", to: 'users#check_email'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    resources :replies
    resources :likes
    resources :posts do
      resources :comments do
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, as: :likeable
  has_many :comments, dependent: :destroy
  has_many :replies, as: :replyable
  validates :message, presence: true, length: { maximum: 200 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :require_user

	def index
		@posts = @user.posts.where(user_id: @user)
	end

	def show
		@post = @user.posts.find(params[:id])
    @posts = @user.posts
  end

  def new
    @post = @user.posts.new
	end

	def edit
		@post = @user.posts.find(params[:id])
	end

	def create
		@post = @user.posts.new(post_params)
		# if @post.save
		# 	redirect_to user_post_path(@user, @post)
		# else
		# 	render 'new'
		# end
    @post.save
	end

	def update
		@post = @user.posts.find(params[:id])
		if @post.update(post_params)
      respond_to do |format|
        format.html { redirect_to user_post_path(@user, @post) }
        format.js {}
      end
		else
			render 'edit'
		end
	end

	def destroy
		@post = @user.posts.find_by(id: params[:id])
    respond_to do |format|
        format.html { redirect_to user_posts_path(@user) }
        format.js {}
    end
    @post.destroy
	end

  def like 
    
  end

	private

		def require_user
			@user = User.find(params[:user_id])
		end

		def post_params
			params.require(:post).permit(:message)
		end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_addcomment.html.erb
<%= link_to(raw('<span class="glyphicon glyphicon-plus"></span> Add Comment'), new_user_post_comment_path(@user, @post), class: "btn btn-info", remote: true) %>

app/views/posts/_edittext.html.erb
<%= post.message %>
<%= link_to "edit", edit_user_post_path(post.user_id, post.id), remote: true %>

app/views/posts/_postform.html.erb
<%= form_for([@user, @post], remote: true) do |user_post| %>
	<% if @post.errors.any? %>
        <div class="error-color" id="error_explanation">
            <h2>
                <%= pluralize(@post.errors.count, "error") %>
            </h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <p>
            <%= user_post.label :message %><br>
            <%= user_post.text_area :message, class: 'form-control', placeholder: 'Message' %>
        </p>
    </div>

	<%= user_post.submit "Post" %>
<% end %>

app/views/posts/create.js.erb
$('#show_comments').append('<p><%= @post.message %></p>');

app/views/posts/destroy.js.erb
$('.post_delete_<%= @post.id %>').remove()

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render 'postform' %>

app/views/posts/edit.js.erb
$('.post_<%= @post.id %>').empty().append("<%= j render partial: 'postform' %>");

app/views/posts/index.html.erb
<div class="panel-group" >
    <h2><%= @user.user_name %> posts: 
        <%= link_to(raw('<span class="glyphicon glyphicon-plus"></span> Add Post'), new_user_post_path(@user), class: "btn btn-info pull-right") %>
    </h2>
    <% @posts.each do |post| %>
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="font-p">Post: <%= post.message %>
                    <%= link_to(raw('<span class="glyphicon glyphicon-remove"></span> Delete Post'), user_post_path(@user,post), class: "btn btn-info pull-right", method: :delete, data: { confirm: 'Are you sure' } ) %>
                    <%= link_to(raw('<span class="glyphicon glyphicon-edit"></span> Edit Post'), edit_user_post_path(@user,post), class: "btn btn-info pull-right") %>
                    <%= link_to(raw('<span class="glyphicon glyphicon-arrow-right"></span> Show Post'), user_post_path(@user,post), class: "btn btn-info pull-right") %>         
                </div>
            </div>
            <div class="panel-body">
                <p class="font-p1">Comments:</p>
                <ul>
                    <% post.comments.each do |comment| %>
                        <% if comment.id %>
                            <li class="comment-height"><%= comment.text %>
                                <%= link_to(raw('<span class="glyphicon glyphicon-remove"></span> Delete Comment'), [@user, post, comment], class: "btn btn-info pull-right btn-sm comment-height", method: :delete, data: { confirm: 'Are you sure' } ) %>
                            </li>
                        <% end %>
                    <% end %>
                </ul>

                <%= form_for([@user, post, post.comments.build], local: true) do |post_comment| %>
                    <div class="error-color">
                        <% flash.each do |name, msg| %>
                            <%= content_tag :div, msg %>
                        <% end %>
                    </div>
                    <div class="form-group">
                        <p>
                            <%= post_comment.text_area :text, class: 'form-control', placeholder: 'Enter comment' %>
                        </p>
                    </div>
                    <span class="pull-right"><%= post_comment.submit "Comment" %></span>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= render 'postform' %>

app/views/posts/show.html.erb
<div class="panel-group">
    <h2>
        <%= @user.user_name %>
    </h2>
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="font-p">Post: <%= @post.message %>
                <%= link_to(raw('<span class="glyphicon glyphicon-edit"></span> Edit Post'), edit_user_post_path(@user,@post), class: "btn btn-info pull-right") %>
                <%= link_to(raw('<span class="glyphicon glyphicon-list"></span> All Posts'), user_posts_path(@user), class: "btn btn-info pull-right") %>         
            </div>
        </div>
        <div class="panel-body">
            <p class="font-p1">Comments:</p>
            <table class="table">
                <tr>
                    <td id='show_comments'>
                        <%= render @post.comments %>
                    </td>
                </tr>
            </table>
            <div id='add_comment'>
                <%= render 'addcomment', locals: { user: @user, post: @post } %>
            </div>
            <div id="add_delete_form">
            </div>
        </div>
    </div>
</div>

<div id='show_post'>
    <% @posts.each do |post|%>
        <div class="post_delete_<%= post.id %>">
            <div class="post_<%= post.id %>">
                <%= render 'edittext', post: post %>
            </div>
            <% if post.id != @post.id %>
                <%= link_to "delete", user_post_path(post.user_id, post.id), method: :delete, remote: true %>
            <% end %>
        </div>
    <% end %>
</div>

app/views/posts/update.js.erb
$('.post_<%= @post.id %>').empty().append("<%= j render partial: 'edittext', locals: { post: @post } %>");